name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Publish website artifact
        uses: actions/upload-artifact@v3
        with:
          name: trunk-based-website
          path: website

  devDeploy:
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: Development
    secrets:
      envPAT: ${{ secrets.envPAT }}


